# Generated by Django 5.2 on 2025-05-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
